# Generated by Django 4.2.13 on 2024-06-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airwayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('shipper_address', models.TextField(blank=True, default='')),
                ('awb_no', models.CharField(blank=True, default='', max_length=100)),
                ('issued_by', models.CharField(blank=True, default='', max_length=100)),
                ('consignee_name', models.CharField(blank=True, default='', max_length=255)),
                ('consignee_address', models.TextField(blank=True, default='')),
                ('issuing_agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('issuing_agent_city', models.CharField(blank=True, default='', max_length=2055)),
                ('accounting_information', models.CharField(blank=True, default='', max_length=2055)),
                ('agent_aita_code', models.CharField(blank=True, max_length=50)),
                ('agent_account_no', models.CharField(blank=True, default='', max_length=100)),
                ('airport_departure', models.CharField(blank=True, default='', max_length=100)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('optional_shipping_info1', models.CharField(blank=True, default='', max_length=255)),
                ('optional_shipping_info2', models.CharField(blank=True, default='', max_length=255)),
                ('to', models.CharField(blank=True, default='', max_length=100)),
                ('by_first_carrier', models.CharField(blank=True, default='', max_length=100)),
                ('to_after_by_first_carrier', models.CharField(blank=True, default='', max_length=100)),
                ('by_after_carrier', models.CharField(blank=True, default='', max_length=100)),
                ('to_after_to_after_carrier', models.CharField(blank=True, default='', max_length=100)),
                ('by_after_by_after_carrier', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('chgs_code', models.CharField(blank=True, default='', max_length=10)),
                ('wt_ppd', models.CharField(blank=True, default='', max_length=10)),
                ('wt_col', models.CharField(blank=True, default='', max_length=10)),
                ('other_ppd', models.CharField(blank=True, default='', max_length=10)),
                ('other_col', models.CharField(blank=True, default='', max_length=10)),
                ('declared_val_carriage', models.CharField(blank=True, default='', max_length=10)),
                ('declared_val_customse', models.CharField(blank=True, default='', max_length=10)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('flight_date', models.DateField(blank=True)),
                ('flight_date_carrier', models.CharField(blank=True, default='', max_length=100)),
                ('amount_insurance', models.CharField(blank=True, default='', max_length=255)),
                ('handling_information', models.TextField(blank=True, default='')),
                ('no_of_pieces', models.PositiveIntegerField(blank=True)),
                ('gross_weight', models.CharField(blank=True, default='', max_length=255)),
                ('kg_lb', models.CharField(blank=True, default='', max_length=10)),
                ('rate_class_commodity_item_no', models.CharField(blank=True, default='', max_length=100)),
                ('chargeable_weight', models.CharField(blank=True, default='', max_length=255)),
                ('rate_charge', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.CharField(blank=True, default='', max_length=255)),
                ('nature_of_goods', models.TextField(blank=True, default='')),
                ('prepaid', models.CharField(blank=True, default='', max_length=255)),
                ('collect', models.CharField(blank=True, default='', max_length=255)),
                ('val_change1', models.CharField(blank=True, default='', max_length=255)),
                ('val_change2', models.CharField(blank=True, default='', max_length=255)),
                ('tax1', models.CharField(blank=True, default='', max_length=255)),
                ('tot_chg_due_agent1', models.CharField(blank=True, default='', max_length=255)),
                ('tot_chg_due_agent2', models.CharField(blank=True, default='', max_length=255)),
                ('tot_chg_due_carrier', models.CharField(blank=True, default='', max_length=255)),
                ('tot_chg_due_carrier2', models.CharField(blank=True, default='', max_length=255)),
                ('total_prepaid_bottom', models.CharField(blank=True, default='', max_length=255)),
                ('total_collect_bottom', models.CharField(blank=True, default='', max_length=255)),
                ('curr_conversion_rate', models.CharField(blank=True, default='', max_length=255)),
                ('cc_changes', models.CharField(blank=True, default='', max_length=255)),
                ('carrier_at_destination', models.CharField(blank=True, default='', max_length=255)),
                ('charges_at_destination', models.CharField(blank=True, default='', max_length=255)),
                ('other_charges', models.CharField(blank=True, max_length=2055)),
                ('total_collect_charges', models.CharField(blank=True, default='', max_length=255)),
                ('total_no_of_pieces', models.PositiveIntegerField(blank=True)),
                ('total_gross_weight', models.CharField(blank=True, default='', max_length=255)),
                ('total_total', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
