# Generated by Django 4.2.13 on 2024-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awbfillerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='no_of_pieces',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
