# Generated by Django 4.2.13 on 2024-06-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awbfillerapp', '0003_alter_airwaybill_total_no_of_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='awb_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='flight_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
