# Generated by Django 4.2.13 on 2024-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awbfillerapp', '0004_alter_airwaybill_awb_no_alter_airwaybill_flight_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airwaybill',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='awb_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
